version: '3'
services:
  lecture-db:
    image: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testlecture
    ports:
      - "5433:5432"
